[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm ci && npm run build"

[build.environment]
  VITE_BACKEND_URL = "https://chess-v4-production.up.railway.app"
  VITE_WEBSOCKET_URL = "https://chess-v4-production.up.railway.app"
  VITE_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"