[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "${{ RAILWAY_PUBLIC_PORT || 3001 }}"
FRONTEND_URL = "${{ FRONTEND_URL }}"
SESSION_SECRET = "${{ SESSION_SECRET }}"

[runtime]
start = "node server.js"